### ISSUE TITLE
Add (dynamic) Footer to all pages

### ISSUE THREAD

**Issue by elwinschmitz** [rodekruis/helpful-information#1013]
A section of (dynamic, markdown) content visible on ALL pages.
Signaling "authorship", "responsibility" and "ownership" of the data on the website/instance.

- Section with margin above it
- All dynamic content from the sheet (from 1 field)
  - list-items
  - links to internal URLs
  - links to external URLs (WhatsApp-Helpdesk, `mailto`-link? feedback-form? etc..)
  - static copyright notice, etc.
- Contains a logo (image included via Markdown/HTML (for now))

```[tasklist]
### Tasks
- [x] Add dynamic footer-component
- [x] Add content from ENV
- [x] Add content from Sheet
- [x] Add 'real' "About"-page from ENV
- [x] Add 'real' "Privacy"-page from ENV
- [x] Prepare all ENVs with static About/Privacy pages
```

**Comment by elwinschmitz** [comment]
See: https://github.com/rodekruis/helpful-information/blob/main/CHANGELOG.md#2024-06-03-v2406
