### ISSUE TITLE
Checklist for deploying HIA in emergencies

### ISSUE THREAD

**Issue by jmargutt** [rodekruis/helpful-information#525]
### **Who requested this spike**
Jacopo Margutti

### **User Story**
As a IM officer deployed on the field,
I want to set up HIA from scratch,
So that it can be used by IFRC/NS.

### **Acceptance Criteria**
- Clear checklist of what needs to be done.
- Checklist is tested with at least 2 people in the NLRC IM roster.

## To Do
- [x] Write guide/checklist
- [x] Change `HIA-demo-site` into `helpful-information-starter`-template-repo
  - [x] Use variables in workflow-file(s)
  - [x] Add multiple/optional deploy workflows (as sub-dir, as standalone, as Azure Static Web App, etc)
- [ ] Set up `/docs`-folder to deploy to GitHub-Pages
- [ ] Share public URL for review with NLRC IMs
- [x] Revise/update guide

**Comment by elwinschmitz** [comment]
@jmargutt Sneak preview: https://github.com/rodekruis/helpful-information/blob/525-checklist-for-deploying-hia-in-emergencies/docs/Guide-How_to_set_up_an_instance.md

**Comment by elwinschmitz** [comment]
Possibly also include something using: https://www.tango.us/

**Comment by jmargutt** [comment]
amazing! thanks @elwinschmitz! let me know when you think this is ready for an "acceptance test" by a non-developer, i.e. just follow instructions and see if they manage.

**Comment by jmargutt** [comment]
@elwinschmitz can you give me an ETA on this item?

**Comment by jmargutt** [comment]
@elwinschmitz reminder: can you give me an ETA on this item or can you tell me who should I ask this to?

**Comment by elwinschmitz** [comment]
Notes:

- include required 'roles' / people
- mention control over content (CEA)
-

**Comment by elwinschmitz** [comment]
Comments

- [ ] Add example workflow-files as template, not in `.github/`-folder.  
  Mention in the set-up steps that you should copy + change the file. (only the one you want)
- [ ] Add comments for each ENV-variable (inline!)
- [ ] Also for Robots.txt + 'Static-regions'-steps
- [ ] Fix typo in `{{ github.* }}` variables
- [ ] Mention in checklist to ENABLE "Pages" in target-repo (use "GitHub Actions workflow"-mode)
- [ ] Fix: filename in push-trigger-array
- [ ] Make  API-key restrictions optional(?)
- [ ]

**Comment by elwinschmitz** [comment]
@jmargutt See: https://github.com/helpful-info for the complete/new flow.
