### ISSUE TITLE
Add translation/language-switch button/widget

### ISSUE THREAD

**Issue by elwinschmitz** [rodekruis/helpful-information#638]
Use direct link/switch:

    https://translate.google.com/translate?u=https://example.org/specific-url

Set "Source Language" (`sl=`) and "Target Language" (`tl=`)

    https://translate.google.com/translate?sl=   en   &tl=   nl   &u=https://example.org/en/english-specific-url

See: https://github.com/rodekruis/helpful-information/issues/601#issuecomment-1461790421

## To Do
- [x] Add "sheet language" to ReferalPage-sheet, i.e: `en`
  - [x] Set `html[lang]`-attribute to use it
- [x] Add "translation presets" to ReferralPage-sheet, i.e: `nl=Nederlands, es=Español, ar=Arabic`
- [x] Add switch-links in Header/Footer
  - [x] ? Icon + drop-down in header?
  - [x] ? List with text at bottom-of-page  
    "Translate with Google Translate in: [Nederlands](#nl), [Español](#es), [Arabic](#ar)"

---

## Solution: Switcher/drop-down in Top-bar (right)
- Use a pre-defined set of target-languages?
  - Needs lang/locale + labels

---

```[tasklist]
### Tasks
- [x] Rebase/update code from PR on top of recent version
- [x] Move logo to start(left) of header
- [x] Move Language-switcher to end(right) of header
- [x] Tweak App/Page-title
- [x] Remove Back-button + logic/magic
- [x] Check other design changes
- [x] Check/prepare Sheet/Data changes required
- [x] Create "implementation/deployment"-issue + task-list
- [x] Check/Add metrics
```

```[tasklist]
### Implement/Deploy
- [x] Instance Demo: Test/Development
- [x] Instance Demo: Staging/Demo/Example
- [x] Instance Demo: Example
- [x] Instance Demo:  Example Multilingual
- [x] Instance Demo: <Emergency>-template
- [x] Instance UM
- [x] Instance FAQ: (empty/off)
- [x] Instance FAQ-Internal: (empty/off)
- [x] Instance OCW: empty/off (for now)
- [x] Instance FAU: empty/off (for now)
- [x] Instance KG: empty/off (for now)
```

**Comment by elwinschmitz** [comment]
See: https://www.flagsarenotlanguages.com/blog/best-practice-for-presenting-languages/

**Comment by JLijftogt** [comment]
Update Elwin/Jonath: working session planned for Elwin/Anca on Monday 4 Dec. Can be finalized by the end of that day.

**Comment by elwinschmitz** [comment]
See https://github.com/rodekruis/helpful-information/blob/main/CHANGELOG.md#2024-06-03-v2406
