### ISSUE TITLE
Add "regions are alternative languages"-mode (via ENV config)

### ISSUE THREAD

**Issue by elwinschmitz** [rodekruis/helpful-information#762]
Following #638 

This would enable the "language-switcher"-component but with 'preset' data from the ENV, not from the Config-sheet. (Also without the  use of Google Translate!)

So:

1. Default-mode

  - If `#locale.alternatives` has valid data in the Config-sheet;
  - Show the Language-Switcher based on these options.
  - Using Google Translate URLs using `source/target Language` from Config-sheet

3. LanguagesAsRegions-mode

  - Any `#locale.alternatives` value(s) will be ignored
  - Language-Switcher options will be based on `REGION`-keys and `REGION_LABELS`
  - Language-Switcher target-URLs replace `/<region>/`-part of URL only.
    So assumes same (Sub-)Categories/Offers.

  - ~~(optional) Auto-detect when `REGION`-keys are all 2 characters long?~~ no magic.

---

```[tasklist]
### Tasks
- [x] Add ENV-variable + documentation
- [x] Create local test/mock data for this mode?
- [x] Create 'switch' logic
- [x] How to create Demo-environment? (Create multiple sheets in IFRC-languages)
- [x] Create implementation/deployment task/step for OCW+FAU+KG
```

```[tasklist]
### Implement/Deploy
- [x] Update deploy-production-ocw: (Add ENV)
- [x] Update FAU: Update to v24.2 + add ENV
- [x] Update KG Update to v24.2 + add ENV
- [x] Create new Demo: Update to v24.2 + add ENV (with local data-files only!)
```

**Comment by elwinschmitz** [comment]
- Add `hreflang="x-default"`. 
- Use link for 'current/selected'. (All in one list of equal links)
- Move `aria-current` to link
- Remove commented-out icon
- Fix prettier-syntax of svgs
-

**Comment by elwinschmitz** [comment]
See https://github.com/rodekruis/helpful-information/blob/main/CHANGELOG.md#2024-06-03-v2406
