### ISSUE TITLE
Improve/enable print-ability (on desktop)

### ISSUE THREAD

**Issue by elwinschmitz** [rodekruis/helpful-information#766]
```[tasklist]
### Tasks
- [x] 'enable' / add generic print-styles
- [x] auto-exapand all `<details>`?
- [x] add custom styles?
```

**Comment by elwinschmitz** [comment]
Decided NOT to do magic with the `<details>`, because:

- no (simple) cross-browser way to trigger/fix it
- it could annoy users that want to explicitly "only print 2 specific answers" on very long pages
- less code overall
