### ISSUE TITLE
Upgrade dependencies (Angular, Node.js, etc...)

### ISSUE THREAD

**Issue by elwinschmitz** [rodekruis/helpful-information#90]
We need to start using more recent versions of all these tools to be sure the app can be reliably build for production-use, but also to ease the process of (new) developers.

# To Do
- [x] Set/document our use of Node.js version (stick to v14-LTS for now)
  - [x] Include a `.node-version`/`.nvmrc`-file + relevant instructions (See [CPDW README](https://github.com/rodekruis/cash-program-design-wizard/blob/main/README.md#getting-started))
- [x] Upgrade to Angular v8
  - [x] Following this checklist: https://update.angular.io/?l=3&v=7.2-8.2
- [x] (optional) Upgrade to the "latest-v4"-version of Ionic (This could be a blocking issue of the "upgrade Angular"-step)
- [x] Set-up automatic dependency-updates via Dependabot
- [x] Use separate API-keys for (local-)development/staging/production (See #94 )
- [x] Verify/test everything still builds as we want
  - [x] Locally on Windows/macOS/Linux
  - [x] On the Azure Static Web App staging/production-environments
- [x] Measure baseline (BEFORE) of performance. See: #95 
- [x] Measure baseline (AFTER of performance. See: #95
