### ISSUE TITLE
Change colors to 'light theme' using variables to support theming

### ISSUE THREAD

**Issue by elwinschmitz** [rodekruis/helpful-information#943]
Following:
https://www.figma.com/file/wdv3l0H80HUYPMgJL05yqq/HIA-design-changes-based-on-research-12%2F23?type=design&node-id=67-7046&mode=design&t=LsyEm5Hf8dKLeqI3-0

```[tasklist]
### Tasks
- [x] Align with Design on NLRC-brand-colors
- [x] Define color-names/functions
- [x] Check/plan configuration-options (Via ENV) →  add to README
- [x] Apply to page
- [x] Apply to components (`.action`, ...)
- [ ] Tweak text-sizes (everywhere)
- [x] Tweak margins/padding (everywhere)
```

**Comment by elwinschmitz** [comment]
See: https://github.com/rodekruis/helpful-information/blob/main/CHANGELOG.md#2024-06-03-v2406
