### ISSUE TITLE
Show Region-name/start/to-parent link (Breadcrumbs refactor)

### ISSUE THREAD

**Issue by elwinschmitz** [rodekruis/helpful-information#944]
Conversion of "Breadcrumbs"-component to "Navigate-to-Parent"-component.

- Shows 1-level-up only
- (possibly?)  Not visible on mobile/narrow-screens

```[tasklist]
### Tasks
- [x] Create new "Up To Parent"-component
- [x] How to handle Region-label (length)?
- [x] Add to Category/Sub-Category/Offer-pages
- [x] ~~Remove "Breadcrumbs"-component + related logic~~
- [x] ~~For "single sub-categories", go 2 levels up~~
```

**Comment by elwinschmitz** [comment]
See https://github.com/rodekruis/helpful-information/blob/main/CHANGELOG.md#2024-06-03-v2406
